add_newline = false
format = """\
  $rust\
  $nodejs\
  $golang\
  $directory\
  $git_branch\
  [❯ ](bold red)\
  """

[git_branch]
format = '[⚡$branch ](bold red)'


[directory]
style = 'bold blue'

[nodejs]
format = '[\[ $version\]](bold black) '

[golang]
format = '[\[󰟓 $version\]](bold black) '

[rust]
format = '[\[ $version\]](bold black) '
